name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci --legacy-peer-deps
    
    - name: Run tests
      run: npm test -- --coverage --watchAll=false
      env:
        CI: true
    
    - name: Build React app
      run: npm run build
    
    - name: Build and release Electron app
      run: npm run electron-pack
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Upload release artifacts
      uses: actions/upload-artifact@v4
      with:
        name: release-${{ matrix.os }}
        path: dist/
        retention-days: 90

  create-release:
    needs: release
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Download all artifacts
      uses: actions/download-artifact@v4
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          release-ubuntu-latest/**/*
          release-windows-latest/**/*
          release-macos-latest/**/*
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  notify:
    needs: [release, create-release]
    runs-on: ubuntu-latest
    
    steps:
    - name: Notify release completion
      run: |
        echo "Release ${{ github.ref_name }} completed successfully!"
        echo "Artifacts uploaded for all platforms"
        # Add notification logic here (Slack, email, etc.)